-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.1 (win64) Build 3865809 Sun May  7 15:05:29 MDT 2023
-- Date        : Tue Jun 18 18:37:57 2024
-- Host        : DESKTOP-FP1C80A running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Users/catal/Vivado/LU-decomposition/LU-decomposition/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_decompose_0_0/design_1_decompose_0_0_stub.vhdl
-- Design      : design_1_decompose_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_decompose_0_0 is
  Port ( 
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 4 downto 0 );
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 4 downto 0 );
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_r_AWADDR : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_control_r_AWVALID : in STD_LOGIC;
    s_axi_control_r_AWREADY : out STD_LOGIC;
    s_axi_control_r_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_r_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_r_WVALID : in STD_LOGIC;
    s_axi_control_r_WREADY : out STD_LOGIC;
    s_axi_control_r_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_r_BVALID : out STD_LOGIC;
    s_axi_control_r_BREADY : in STD_LOGIC;
    s_axi_control_r_ARADDR : in STD_LOGIC_VECTOR ( 8 downto 0 );
    s_axi_control_r_ARVALID : in STD_LOGIC;
    s_axi_control_r_ARREADY : out STD_LOGIC;
    s_axi_control_r_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_r_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_r_RVALID : out STD_LOGIC;
    s_axi_control_r_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem_0_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_0_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_0_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_AWVALID : out STD_LOGIC;
    m_axi_gmem_0_AWREADY : in STD_LOGIC;
    m_axi_gmem_0_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_0_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_0_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_WLAST : out STD_LOGIC;
    m_axi_gmem_0_WVALID : out STD_LOGIC;
    m_axi_gmem_0_WREADY : in STD_LOGIC;
    m_axi_gmem_0_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_BVALID : in STD_LOGIC;
    m_axi_gmem_0_BREADY : out STD_LOGIC;
    m_axi_gmem_0_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_0_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_0_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_0_ARVALID : out STD_LOGIC;
    m_axi_gmem_0_ARREADY : in STD_LOGIC;
    m_axi_gmem_0_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_0_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_0_RLAST : in STD_LOGIC;
    m_axi_gmem_0_RVALID : in STD_LOGIC;
    m_axi_gmem_0_RREADY : out STD_LOGIC;
    m_axi_gmem_1_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_1_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_1_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_AWVALID : out STD_LOGIC;
    m_axi_gmem_1_AWREADY : in STD_LOGIC;
    m_axi_gmem_1_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_1_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_1_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_WLAST : out STD_LOGIC;
    m_axi_gmem_1_WVALID : out STD_LOGIC;
    m_axi_gmem_1_WREADY : in STD_LOGIC;
    m_axi_gmem_1_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_BVALID : in STD_LOGIC;
    m_axi_gmem_1_BREADY : out STD_LOGIC;
    m_axi_gmem_1_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_1_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_1_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_1_ARVALID : out STD_LOGIC;
    m_axi_gmem_1_ARREADY : in STD_LOGIC;
    m_axi_gmem_1_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_1_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_1_RLAST : in STD_LOGIC;
    m_axi_gmem_1_RVALID : in STD_LOGIC;
    m_axi_gmem_1_RREADY : out STD_LOGIC;
    m_axi_gmem_2_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_2_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_2_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_AWVALID : out STD_LOGIC;
    m_axi_gmem_2_AWREADY : in STD_LOGIC;
    m_axi_gmem_2_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_WLAST : out STD_LOGIC;
    m_axi_gmem_2_WVALID : out STD_LOGIC;
    m_axi_gmem_2_WREADY : in STD_LOGIC;
    m_axi_gmem_2_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_BVALID : in STD_LOGIC;
    m_axi_gmem_2_BREADY : out STD_LOGIC;
    m_axi_gmem_2_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_2_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_2_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_2_ARVALID : out STD_LOGIC;
    m_axi_gmem_2_ARREADY : in STD_LOGIC;
    m_axi_gmem_2_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_2_RLAST : in STD_LOGIC;
    m_axi_gmem_2_RVALID : in STD_LOGIC;
    m_axi_gmem_2_RREADY : out STD_LOGIC;
    m_axi_gmem_3_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_3_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_3_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_AWVALID : out STD_LOGIC;
    m_axi_gmem_3_AWREADY : in STD_LOGIC;
    m_axi_gmem_3_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_3_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_3_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_WLAST : out STD_LOGIC;
    m_axi_gmem_3_WVALID : out STD_LOGIC;
    m_axi_gmem_3_WREADY : in STD_LOGIC;
    m_axi_gmem_3_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_BVALID : in STD_LOGIC;
    m_axi_gmem_3_BREADY : out STD_LOGIC;
    m_axi_gmem_3_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_3_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_3_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_3_ARVALID : out STD_LOGIC;
    m_axi_gmem_3_ARREADY : in STD_LOGIC;
    m_axi_gmem_3_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_3_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_3_RLAST : in STD_LOGIC;
    m_axi_gmem_3_RVALID : in STD_LOGIC;
    m_axi_gmem_3_RREADY : out STD_LOGIC;
    m_axi_gmem_4_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_4_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_4_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_4_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_4_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_4_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_AWVALID : out STD_LOGIC;
    m_axi_gmem_4_AWREADY : in STD_LOGIC;
    m_axi_gmem_4_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_4_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_4_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_WLAST : out STD_LOGIC;
    m_axi_gmem_4_WVALID : out STD_LOGIC;
    m_axi_gmem_4_WREADY : in STD_LOGIC;
    m_axi_gmem_4_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_4_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_BVALID : in STD_LOGIC;
    m_axi_gmem_4_BREADY : out STD_LOGIC;
    m_axi_gmem_4_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_4_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_4_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_4_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_4_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_4_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_4_ARVALID : out STD_LOGIC;
    m_axi_gmem_4_ARREADY : in STD_LOGIC;
    m_axi_gmem_4_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_4_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_4_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_4_RLAST : in STD_LOGIC;
    m_axi_gmem_4_RVALID : in STD_LOGIC;
    m_axi_gmem_4_RREADY : out STD_LOGIC;
    m_axi_gmem_5_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_5_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_5_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_5_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_5_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_5_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_AWVALID : out STD_LOGIC;
    m_axi_gmem_5_AWREADY : in STD_LOGIC;
    m_axi_gmem_5_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_5_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_5_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_WLAST : out STD_LOGIC;
    m_axi_gmem_5_WVALID : out STD_LOGIC;
    m_axi_gmem_5_WREADY : in STD_LOGIC;
    m_axi_gmem_5_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_5_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_BVALID : in STD_LOGIC;
    m_axi_gmem_5_BREADY : out STD_LOGIC;
    m_axi_gmem_5_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_5_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_5_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_5_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_5_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_5_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_5_ARVALID : out STD_LOGIC;
    m_axi_gmem_5_ARREADY : in STD_LOGIC;
    m_axi_gmem_5_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_5_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_5_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_5_RLAST : in STD_LOGIC;
    m_axi_gmem_5_RVALID : in STD_LOGIC;
    m_axi_gmem_5_RREADY : out STD_LOGIC;
    m_axi_gmem_6_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_6_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_6_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_6_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_6_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_6_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_AWVALID : out STD_LOGIC;
    m_axi_gmem_6_AWREADY : in STD_LOGIC;
    m_axi_gmem_6_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_6_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_6_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_WLAST : out STD_LOGIC;
    m_axi_gmem_6_WVALID : out STD_LOGIC;
    m_axi_gmem_6_WREADY : in STD_LOGIC;
    m_axi_gmem_6_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_6_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_BVALID : in STD_LOGIC;
    m_axi_gmem_6_BREADY : out STD_LOGIC;
    m_axi_gmem_6_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_6_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_6_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_6_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_6_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_6_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_6_ARVALID : out STD_LOGIC;
    m_axi_gmem_6_ARREADY : in STD_LOGIC;
    m_axi_gmem_6_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_6_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_6_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_6_RLAST : in STD_LOGIC;
    m_axi_gmem_6_RVALID : in STD_LOGIC;
    m_axi_gmem_6_RREADY : out STD_LOGIC;
    m_axi_gmem_7_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_7_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_7_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_7_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_7_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_7_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_AWVALID : out STD_LOGIC;
    m_axi_gmem_7_AWREADY : in STD_LOGIC;
    m_axi_gmem_7_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_7_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_7_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_WLAST : out STD_LOGIC;
    m_axi_gmem_7_WVALID : out STD_LOGIC;
    m_axi_gmem_7_WREADY : in STD_LOGIC;
    m_axi_gmem_7_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_7_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_BVALID : in STD_LOGIC;
    m_axi_gmem_7_BREADY : out STD_LOGIC;
    m_axi_gmem_7_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_7_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_7_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_7_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_7_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_7_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_7_ARVALID : out STD_LOGIC;
    m_axi_gmem_7_ARREADY : in STD_LOGIC;
    m_axi_gmem_7_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_7_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_7_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_7_RLAST : in STD_LOGIC;
    m_axi_gmem_7_RVALID : in STD_LOGIC;
    m_axi_gmem_7_RREADY : out STD_LOGIC
  );

end design_1_decompose_0_0;

architecture stub of design_1_decompose_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_control_AWADDR[4:0],s_axi_control_AWVALID,s_axi_control_AWREADY,s_axi_control_WDATA[31:0],s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_control_WREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_BREADY,s_axi_control_ARADDR[4:0],s_axi_control_ARVALID,s_axi_control_ARREADY,s_axi_control_RDATA[31:0],s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_RREADY,s_axi_control_r_AWADDR[8:0],s_axi_control_r_AWVALID,s_axi_control_r_AWREADY,s_axi_control_r_WDATA[31:0],s_axi_control_r_WSTRB[3:0],s_axi_control_r_WVALID,s_axi_control_r_WREADY,s_axi_control_r_BRESP[1:0],s_axi_control_r_BVALID,s_axi_control_r_BREADY,s_axi_control_r_ARADDR[8:0],s_axi_control_r_ARVALID,s_axi_control_r_ARREADY,s_axi_control_r_RDATA[31:0],s_axi_control_r_RRESP[1:0],s_axi_control_r_RVALID,s_axi_control_r_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_gmem_0_AWID[0:0],m_axi_gmem_0_AWADDR[63:0],m_axi_gmem_0_AWLEN[7:0],m_axi_gmem_0_AWSIZE[2:0],m_axi_gmem_0_AWBURST[1:0],m_axi_gmem_0_AWLOCK[1:0],m_axi_gmem_0_AWREGION[3:0],m_axi_gmem_0_AWCACHE[3:0],m_axi_gmem_0_AWPROT[2:0],m_axi_gmem_0_AWQOS[3:0],m_axi_gmem_0_AWVALID,m_axi_gmem_0_AWREADY,m_axi_gmem_0_WID[0:0],m_axi_gmem_0_WDATA[31:0],m_axi_gmem_0_WSTRB[3:0],m_axi_gmem_0_WLAST,m_axi_gmem_0_WVALID,m_axi_gmem_0_WREADY,m_axi_gmem_0_BID[0:0],m_axi_gmem_0_BRESP[1:0],m_axi_gmem_0_BVALID,m_axi_gmem_0_BREADY,m_axi_gmem_0_ARID[0:0],m_axi_gmem_0_ARADDR[63:0],m_axi_gmem_0_ARLEN[7:0],m_axi_gmem_0_ARSIZE[2:0],m_axi_gmem_0_ARBURST[1:0],m_axi_gmem_0_ARLOCK[1:0],m_axi_gmem_0_ARREGION[3:0],m_axi_gmem_0_ARCACHE[3:0],m_axi_gmem_0_ARPROT[2:0],m_axi_gmem_0_ARQOS[3:0],m_axi_gmem_0_ARVALID,m_axi_gmem_0_ARREADY,m_axi_gmem_0_RID[0:0],m_axi_gmem_0_RDATA[31:0],m_axi_gmem_0_RRESP[1:0],m_axi_gmem_0_RLAST,m_axi_gmem_0_RVALID,m_axi_gmem_0_RREADY,m_axi_gmem_1_AWID[0:0],m_axi_gmem_1_AWADDR[63:0],m_axi_gmem_1_AWLEN[7:0],m_axi_gmem_1_AWSIZE[2:0],m_axi_gmem_1_AWBURST[1:0],m_axi_gmem_1_AWLOCK[1:0],m_axi_gmem_1_AWREGION[3:0],m_axi_gmem_1_AWCACHE[3:0],m_axi_gmem_1_AWPROT[2:0],m_axi_gmem_1_AWQOS[3:0],m_axi_gmem_1_AWVALID,m_axi_gmem_1_AWREADY,m_axi_gmem_1_WID[0:0],m_axi_gmem_1_WDATA[31:0],m_axi_gmem_1_WSTRB[3:0],m_axi_gmem_1_WLAST,m_axi_gmem_1_WVALID,m_axi_gmem_1_WREADY,m_axi_gmem_1_BID[0:0],m_axi_gmem_1_BRESP[1:0],m_axi_gmem_1_BVALID,m_axi_gmem_1_BREADY,m_axi_gmem_1_ARID[0:0],m_axi_gmem_1_ARADDR[63:0],m_axi_gmem_1_ARLEN[7:0],m_axi_gmem_1_ARSIZE[2:0],m_axi_gmem_1_ARBURST[1:0],m_axi_gmem_1_ARLOCK[1:0],m_axi_gmem_1_ARREGION[3:0],m_axi_gmem_1_ARCACHE[3:0],m_axi_gmem_1_ARPROT[2:0],m_axi_gmem_1_ARQOS[3:0],m_axi_gmem_1_ARVALID,m_axi_gmem_1_ARREADY,m_axi_gmem_1_RID[0:0],m_axi_gmem_1_RDATA[31:0],m_axi_gmem_1_RRESP[1:0],m_axi_gmem_1_RLAST,m_axi_gmem_1_RVALID,m_axi_gmem_1_RREADY,m_axi_gmem_2_AWID[0:0],m_axi_gmem_2_AWADDR[63:0],m_axi_gmem_2_AWLEN[7:0],m_axi_gmem_2_AWSIZE[2:0],m_axi_gmem_2_AWBURST[1:0],m_axi_gmem_2_AWLOCK[1:0],m_axi_gmem_2_AWREGION[3:0],m_axi_gmem_2_AWCACHE[3:0],m_axi_gmem_2_AWPROT[2:0],m_axi_gmem_2_AWQOS[3:0],m_axi_gmem_2_AWVALID,m_axi_gmem_2_AWREADY,m_axi_gmem_2_WID[0:0],m_axi_gmem_2_WDATA[31:0],m_axi_gmem_2_WSTRB[3:0],m_axi_gmem_2_WLAST,m_axi_gmem_2_WVALID,m_axi_gmem_2_WREADY,m_axi_gmem_2_BID[0:0],m_axi_gmem_2_BRESP[1:0],m_axi_gmem_2_BVALID,m_axi_gmem_2_BREADY,m_axi_gmem_2_ARID[0:0],m_axi_gmem_2_ARADDR[63:0],m_axi_gmem_2_ARLEN[7:0],m_axi_gmem_2_ARSIZE[2:0],m_axi_gmem_2_ARBURST[1:0],m_axi_gmem_2_ARLOCK[1:0],m_axi_gmem_2_ARREGION[3:0],m_axi_gmem_2_ARCACHE[3:0],m_axi_gmem_2_ARPROT[2:0],m_axi_gmem_2_ARQOS[3:0],m_axi_gmem_2_ARVALID,m_axi_gmem_2_ARREADY,m_axi_gmem_2_RID[0:0],m_axi_gmem_2_RDATA[31:0],m_axi_gmem_2_RRESP[1:0],m_axi_gmem_2_RLAST,m_axi_gmem_2_RVALID,m_axi_gmem_2_RREADY,m_axi_gmem_3_AWID[0:0],m_axi_gmem_3_AWADDR[63:0],m_axi_gmem_3_AWLEN[7:0],m_axi_gmem_3_AWSIZE[2:0],m_axi_gmem_3_AWBURST[1:0],m_axi_gmem_3_AWLOCK[1:0],m_axi_gmem_3_AWREGION[3:0],m_axi_gmem_3_AWCACHE[3:0],m_axi_gmem_3_AWPROT[2:0],m_axi_gmem_3_AWQOS[3:0],m_axi_gmem_3_AWVALID,m_axi_gmem_3_AWREADY,m_axi_gmem_3_WID[0:0],m_axi_gmem_3_WDATA[31:0],m_axi_gmem_3_WSTRB[3:0],m_axi_gmem_3_WLAST,m_axi_gmem_3_WVALID,m_axi_gmem_3_WREADY,m_axi_gmem_3_BID[0:0],m_axi_gmem_3_BRESP[1:0],m_axi_gmem_3_BVALID,m_axi_gmem_3_BREADY,m_axi_gmem_3_ARID[0:0],m_axi_gmem_3_ARADDR[63:0],m_axi_gmem_3_ARLEN[7:0],m_axi_gmem_3_ARSIZE[2:0],m_axi_gmem_3_ARBURST[1:0],m_axi_gmem_3_ARLOCK[1:0],m_axi_gmem_3_ARREGION[3:0],m_axi_gmem_3_ARCACHE[3:0],m_axi_gmem_3_ARPROT[2:0],m_axi_gmem_3_ARQOS[3:0],m_axi_gmem_3_ARVALID,m_axi_gmem_3_ARREADY,m_axi_gmem_3_RID[0:0],m_axi_gmem_3_RDATA[31:0],m_axi_gmem_3_RRESP[1:0],m_axi_gmem_3_RLAST,m_axi_gmem_3_RVALID,m_axi_gmem_3_RREADY,m_axi_gmem_4_AWID[0:0],m_axi_gmem_4_AWADDR[63:0],m_axi_gmem_4_AWLEN[7:0],m_axi_gmem_4_AWSIZE[2:0],m_axi_gmem_4_AWBURST[1:0],m_axi_gmem_4_AWLOCK[1:0],m_axi_gmem_4_AWREGION[3:0],m_axi_gmem_4_AWCACHE[3:0],m_axi_gmem_4_AWPROT[2:0],m_axi_gmem_4_AWQOS[3:0],m_axi_gmem_4_AWVALID,m_axi_gmem_4_AWREADY,m_axi_gmem_4_WID[0:0],m_axi_gmem_4_WDATA[31:0],m_axi_gmem_4_WSTRB[3:0],m_axi_gmem_4_WLAST,m_axi_gmem_4_WVALID,m_axi_gmem_4_WREADY,m_axi_gmem_4_BID[0:0],m_axi_gmem_4_BRESP[1:0],m_axi_gmem_4_BVALID,m_axi_gmem_4_BREADY,m_axi_gmem_4_ARID[0:0],m_axi_gmem_4_ARADDR[63:0],m_axi_gmem_4_ARLEN[7:0],m_axi_gmem_4_ARSIZE[2:0],m_axi_gmem_4_ARBURST[1:0],m_axi_gmem_4_ARLOCK[1:0],m_axi_gmem_4_ARREGION[3:0],m_axi_gmem_4_ARCACHE[3:0],m_axi_gmem_4_ARPROT[2:0],m_axi_gmem_4_ARQOS[3:0],m_axi_gmem_4_ARVALID,m_axi_gmem_4_ARREADY,m_axi_gmem_4_RID[0:0],m_axi_gmem_4_RDATA[31:0],m_axi_gmem_4_RRESP[1:0],m_axi_gmem_4_RLAST,m_axi_gmem_4_RVALID,m_axi_gmem_4_RREADY,m_axi_gmem_5_AWID[0:0],m_axi_gmem_5_AWADDR[63:0],m_axi_gmem_5_AWLEN[7:0],m_axi_gmem_5_AWSIZE[2:0],m_axi_gmem_5_AWBURST[1:0],m_axi_gmem_5_AWLOCK[1:0],m_axi_gmem_5_AWREGION[3:0],m_axi_gmem_5_AWCACHE[3:0],m_axi_gmem_5_AWPROT[2:0],m_axi_gmem_5_AWQOS[3:0],m_axi_gmem_5_AWVALID,m_axi_gmem_5_AWREADY,m_axi_gmem_5_WID[0:0],m_axi_gmem_5_WDATA[31:0],m_axi_gmem_5_WSTRB[3:0],m_axi_gmem_5_WLAST,m_axi_gmem_5_WVALID,m_axi_gmem_5_WREADY,m_axi_gmem_5_BID[0:0],m_axi_gmem_5_BRESP[1:0],m_axi_gmem_5_BVALID,m_axi_gmem_5_BREADY,m_axi_gmem_5_ARID[0:0],m_axi_gmem_5_ARADDR[63:0],m_axi_gmem_5_ARLEN[7:0],m_axi_gmem_5_ARSIZE[2:0],m_axi_gmem_5_ARBURST[1:0],m_axi_gmem_5_ARLOCK[1:0],m_axi_gmem_5_ARREGION[3:0],m_axi_gmem_5_ARCACHE[3:0],m_axi_gmem_5_ARPROT[2:0],m_axi_gmem_5_ARQOS[3:0],m_axi_gmem_5_ARVALID,m_axi_gmem_5_ARREADY,m_axi_gmem_5_RID[0:0],m_axi_gmem_5_RDATA[31:0],m_axi_gmem_5_RRESP[1:0],m_axi_gmem_5_RLAST,m_axi_gmem_5_RVALID,m_axi_gmem_5_RREADY,m_axi_gmem_6_AWID[0:0],m_axi_gmem_6_AWADDR[63:0],m_axi_gmem_6_AWLEN[7:0],m_axi_gmem_6_AWSIZE[2:0],m_axi_gmem_6_AWBURST[1:0],m_axi_gmem_6_AWLOCK[1:0],m_axi_gmem_6_AWREGION[3:0],m_axi_gmem_6_AWCACHE[3:0],m_axi_gmem_6_AWPROT[2:0],m_axi_gmem_6_AWQOS[3:0],m_axi_gmem_6_AWVALID,m_axi_gmem_6_AWREADY,m_axi_gmem_6_WID[0:0],m_axi_gmem_6_WDATA[31:0],m_axi_gmem_6_WSTRB[3:0],m_axi_gmem_6_WLAST,m_axi_gmem_6_WVALID,m_axi_gmem_6_WREADY,m_axi_gmem_6_BID[0:0],m_axi_gmem_6_BRESP[1:0],m_axi_gmem_6_BVALID,m_axi_gmem_6_BREADY,m_axi_gmem_6_ARID[0:0],m_axi_gmem_6_ARADDR[63:0],m_axi_gmem_6_ARLEN[7:0],m_axi_gmem_6_ARSIZE[2:0],m_axi_gmem_6_ARBURST[1:0],m_axi_gmem_6_ARLOCK[1:0],m_axi_gmem_6_ARREGION[3:0],m_axi_gmem_6_ARCACHE[3:0],m_axi_gmem_6_ARPROT[2:0],m_axi_gmem_6_ARQOS[3:0],m_axi_gmem_6_ARVALID,m_axi_gmem_6_ARREADY,m_axi_gmem_6_RID[0:0],m_axi_gmem_6_RDATA[31:0],m_axi_gmem_6_RRESP[1:0],m_axi_gmem_6_RLAST,m_axi_gmem_6_RVALID,m_axi_gmem_6_RREADY,m_axi_gmem_7_AWID[0:0],m_axi_gmem_7_AWADDR[63:0],m_axi_gmem_7_AWLEN[7:0],m_axi_gmem_7_AWSIZE[2:0],m_axi_gmem_7_AWBURST[1:0],m_axi_gmem_7_AWLOCK[1:0],m_axi_gmem_7_AWREGION[3:0],m_axi_gmem_7_AWCACHE[3:0],m_axi_gmem_7_AWPROT[2:0],m_axi_gmem_7_AWQOS[3:0],m_axi_gmem_7_AWVALID,m_axi_gmem_7_AWREADY,m_axi_gmem_7_WID[0:0],m_axi_gmem_7_WDATA[31:0],m_axi_gmem_7_WSTRB[3:0],m_axi_gmem_7_WLAST,m_axi_gmem_7_WVALID,m_axi_gmem_7_WREADY,m_axi_gmem_7_BID[0:0],m_axi_gmem_7_BRESP[1:0],m_axi_gmem_7_BVALID,m_axi_gmem_7_BREADY,m_axi_gmem_7_ARID[0:0],m_axi_gmem_7_ARADDR[63:0],m_axi_gmem_7_ARLEN[7:0],m_axi_gmem_7_ARSIZE[2:0],m_axi_gmem_7_ARBURST[1:0],m_axi_gmem_7_ARLOCK[1:0],m_axi_gmem_7_ARREGION[3:0],m_axi_gmem_7_ARCACHE[3:0],m_axi_gmem_7_ARPROT[2:0],m_axi_gmem_7_ARQOS[3:0],m_axi_gmem_7_ARVALID,m_axi_gmem_7_ARREADY,m_axi_gmem_7_RID[0:0],m_axi_gmem_7_RDATA[31:0],m_axi_gmem_7_RRESP[1:0],m_axi_gmem_7_RLAST,m_axi_gmem_7_RVALID,m_axi_gmem_7_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "decompose,Vivado 2023.1";
begin
end;
